import { Contact, Deal, Activity, User, DashboardStats } from '@/types/crm';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@company.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1494791368093-85217fbbf8de?w=400&h=400&fit=crop&crop=face',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2', 
    name: 'Mike Chen',
    email: 'mike@company.com',
    role: 'sales',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    createdAt: new Date('2024-01-15'),
  },
];

// Mock Contacts - 50 contacts
export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@techcorp.com',
    phone: '+1 (555) 123-4567',
    company: 'TechCorp Inc.',
    position: 'CTO',
    status: 'active',
    tags: ['enterprise', 'tech'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-15'),
    assignedTo: '2',
    notes: 'Interested in enterprise solution',
  },
  {
    id: '2',
    name: 'Emily Davis',
    email: 'emily@startup.io',
    phone: '+1 (555) 987-6543',
    company: 'Startup.io',
    position: 'Founder',
    status: 'prospect',
    tags: ['startup', 'saas'],
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-06-16'),
    assignedTo: '2',
  },
  {
    id: '3',
    name: 'Robert Wilson',
    email: 'robert@bigcorp.com',
    phone: '+1 (555) 456-7890',
    company: 'BigCorp',
    position: 'VP Sales',
    status: 'active',
    tags: ['enterprise', 'established'],
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-06-17'),
    assignedTo: '1',
  },
  {
    id: '4',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@healthplus.com',
    phone: '+1 (555) 234-5678',
    company: 'HealthPlus Solutions',
    position: 'Director of Operations',
    status: 'active',
    tags: ['healthcare', 'mid-market'],
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-06-18'),
    assignedTo: '1',
  },
  {
    id: '5',
    name: 'David Martinez',
    email: 'david.martinez@fintech.com',
    phone: '+1 (555) 345-6789',
    company: 'FinTech Innovations',
    position: 'Product Manager',
    status: 'prospect',
    tags: ['fintech', 'innovation'],
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-06-19'),
    assignedTo: '2',
  },
  {
    id: '6',
    name: 'Jennifer Brown',
    email: 'jennifer.brown@retailco.com',
    phone: '+1 (555) 456-7890',
    company: 'RetailCo',
    position: 'Marketing Director',
    status: 'active',
    tags: ['retail', 'marketing'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-20'),
    assignedTo: '1',
  },
  {
    id: '7',
    name: 'Michael Johnson',
    email: 'michael.johnson@educorp.com',
    phone: '+1 (555) 567-8901',
    company: 'EduCorp',
    position: 'VP Technology',
    status: 'prospect',
    tags: ['education', 'technology'],
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-06-21'),
    assignedTo: '2',
  },
  {
    id: '8',
    name: 'Sarah Thompson',
    email: 'sarah.thompson@consulting.com',
    phone: '+1 (555) 678-9012',
    company: 'Thompson Consulting',
    position: 'Senior Partner',
    status: 'active',
    tags: ['consulting', 'enterprise'],
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-22'),
    assignedTo: '1',
  },
  {
    id: '9',
    name: 'Kevin Lee',
    email: 'kevin.lee@logistics.com',
    phone: '+1 (555) 789-0123',
    company: 'Global Logistics',
    position: 'Operations Manager',
    status: 'inactive',
    tags: ['logistics', 'operations'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-05-15'),
    assignedTo: '2',
  },
  {
    id: '10',
    name: 'Amanda Clark',
    email: 'amanda.clark@mediagroup.com',
    phone: '+1 (555) 890-1234',
    company: 'Media Group Inc',
    position: 'Creative Director',
    status: 'prospect',
    tags: ['media', 'creative'],
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-06-23'),
    assignedTo: '1',
  },
  {
    id: '11',
    name: 'Christopher White',
    email: 'chris.white@manufacturing.com',
    phone: '+1 (555) 901-2345',
    company: 'White Manufacturing',
    position: 'Plant Manager',
    status: 'active',
    tags: ['manufacturing', 'industrial'],
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-06-24'),
    assignedTo: '2',
  },
  {
    id: '12',
    name: 'Nicole Garcia',
    email: 'nicole.garcia@pharma.com',
    phone: '+1 (555) 012-3456',
    company: 'PharmaCorp',
    position: 'Research Director',
    status: 'prospect',
    tags: ['pharmaceutical', 'research'],
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-06-25'),
    assignedTo: '1',
  },
  {
    id: '13',
    name: 'Ryan Miller',
    email: 'ryan.miller@energy.com',
    phone: '+1 (555) 123-4567',
    company: 'Green Energy Solutions',
    position: 'Project Manager',
    status: 'active',
    tags: ['energy', 'green-tech'],
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-06-26'),
    assignedTo: '2',
  },
  {
    id: '14',
    name: 'Jessica Taylor',
    email: 'jessica.taylor@insurance.com',
    phone: '+1 (555) 234-5678',
    company: 'Taylor Insurance',
    position: 'Account Executive',
    status: 'prospect',
    tags: ['insurance', 'finance'],
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-27'),
    assignedTo: '1',
  },
  {
    id: '15',
    name: 'Daniel Rodriguez',
    email: 'daniel.rodriguez@construction.com',
    phone: '+1 (555) 345-6789',
    company: 'Rodriguez Construction',
    position: 'Site Supervisor',
    status: 'active',
    tags: ['construction', 'real-estate'],
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-06-28'),
    assignedTo: '2',
  },
  {
    id: '16',
    name: 'Lauren Wilson',
    email: 'lauren.wilson@hospitality.com',
    phone: '+1 (555) 456-7890',
    company: 'Luxury Hospitality Group',
    position: 'General Manager',
    status: 'prospect',
    tags: ['hospitality', 'luxury'],
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-06-29'),
    assignedTo: '1',
  },
  {
    id: '17',
    name: 'Brian Moore',
    email: 'brian.moore@automotive.com',
    phone: '+1 (555) 567-8901',
    company: 'Moore Automotive',
    position: 'Service Manager',
    status: 'active',
    tags: ['automotive', 'service'],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-06-30'),
    assignedTo: '2',
  },
  {
    id: '18',
    name: 'Stephanie Hall',
    email: 'stephanie.hall@legal.com',
    phone: '+1 (555) 678-9012',
    company: 'Hall Legal Services',
    position: 'Managing Partner',
    status: 'prospect',
    tags: ['legal', 'professional-services'],
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-07-01'),
    assignedTo: '1',
  },
  {
    id: '19',
    name: 'Andrew Young',
    email: 'andrew.young@nonprofit.org',
    phone: '+1 (555) 789-0123',
    company: 'Community Foundation',
    position: 'Executive Director',
    status: 'active',
    tags: ['nonprofit', 'community'],
    createdAt: new Date('2024-05-05'),
    updatedAt: new Date('2024-07-02'),
    assignedTo: '2',
  },
  {
    id: '20',
    name: 'Michelle King',
    email: 'michelle.king@fashion.com',
    phone: '+1 (555) 890-1234',
    company: 'King Fashion House',
    position: 'Design Director',
    status: 'prospect',
    tags: ['fashion', 'design'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-07-03'),
    assignedTo: '1',
  },
  {
    id: '21',
    name: 'Thomas Scott',
    email: 'thomas.scott@agriculture.com',
    phone: '+1 (555) 901-2345',
    company: 'Scott Farms',
    position: 'Farm Manager',
    status: 'active',
    tags: ['agriculture', 'farming'],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-07-04'),
    assignedTo: '2',
  },
  {
    id: '22',
    name: 'Rachel Green',
    email: 'rachel.green@publishing.com',
    phone: '+1 (555) 012-3456',
    company: 'Green Publishing',
    position: 'Editor-in-Chief',
    status: 'prospect',
    tags: ['publishing', 'media'],
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-07-05'),
    assignedTo: '1',
  },
  {
    id: '23',
    name: 'Steven Adams',
    email: 'steven.adams@sports.com',
    phone: '+1 (555) 123-4567',
    company: 'Adams Sports Management',
    position: 'Sports Agent',
    status: 'active',
    tags: ['sports', 'entertainment'],
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-07-06'),
    assignedTo: '2',
  },
  {
    id: '24',
    name: 'Kimberly Baker',
    email: 'kimberly.baker@food.com',
    phone: '+1 (555) 234-5678',
    company: 'Baker Foods Inc',
    position: 'Quality Manager',
    status: 'prospect',
    tags: ['food', 'manufacturing'],
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-07-07'),
    assignedTo: '1',
  },
  {
    id: '25',
    name: 'Mark Turner',
    email: 'mark.turner@transport.com',
    phone: '+1 (555) 345-6789',
    company: 'Turner Transport',
    position: 'Fleet Manager',
    status: 'active',
    tags: ['transportation', 'logistics'],
    createdAt: new Date('2024-01-05'),
    updatedTo: new Date('2024-07-08'),
    assignedTo: '2',
  },
  {
    id: '26',
    name: 'Carol Phillips',
    email: 'carol.phillips@beauty.com',
    phone: '+1 (555) 456-7890',
    company: 'Phillips Beauty',
    position: 'Brand Manager',
    status: 'prospect',
    tags: ['beauty', 'cosmetics'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-07-09'),
    assignedTo: '1',
  },
  {
    id: '27',
    name: 'Gregory Campbell',
    email: 'gregory.campbell@telecom.com',
    phone: '+1 (555) 567-8901',
    company: 'Campbell Telecom',
    position: 'Network Engineer',
    status: 'active',
    tags: ['telecom', 'engineering'],
    createdAt: new Date('2024-03-30'),
    updatedAt: new Date('2024-07-10'),
    assignedTo: '2',
  },
  {
    id: '28',
    name: 'Donna Parker',
    email: 'donna.parker@wellness.com',
    phone: '+1 (555) 678-9012',
    company: 'Parker Wellness Center',
    position: 'Director',
    status: 'prospect',
    tags: ['wellness', 'healthcare'],
    createdAt: new Date('2024-04-25'),
    updatedAt: new Date('2024-07-11'),
    assignedTo: '1',
  },
  {
    id: '29',
    name: 'Edward Evans',
    email: 'edward.evans@security.com',
    phone: '+1 (555) 789-0123',
    company: 'Evans Security',
    position: 'Security Manager',
    status: 'active',
    tags: ['security', 'safety'],
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-07-12'),
    assignedTo: '2',
  },
  {
    id: '30',
    name: 'Patricia Collins',
    email: 'patricia.collins@dental.com',
    phone: '+1 (555) 890-1234',
    company: 'Collins Dental Group',
    position: 'Practice Manager',
    status: 'prospect',
    tags: ['dental', 'healthcare'],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-07-13'),
    assignedTo: '1',
  },
  {
    id: '31',
    name: 'Joseph Stewart',
    email: 'joseph.stewart@electronics.com',
    phone: '+1 (555) 901-2345',
    company: 'Stewart Electronics',
    position: 'Technical Director',
    status: 'active',
    tags: ['electronics', 'technology'],
    createdAt: new Date('2024-02-22'),
    updatedAt: new Date('2024-07-14'),
    assignedTo: '2',
  },
  {
    id: '32',
    name: 'Helen Morris',
    email: 'helen.morris@travel.com',
    phone: '+1 (555) 012-3456',
    company: 'Morris Travel Agency',
    position: 'Travel Coordinator',
    status: 'prospect',
    tags: ['travel', 'hospitality'],
    createdAt: new Date('2024-03-08'),
    updatedAt: new Date('2024-07-15'),
    assignedTo: '1',
  },
  {
    id: '33',
    name: 'Charles Rogers',
    email: 'charles.rogers@furniture.com',
    phone: '+1 (555) 123-4567',
    company: 'Rogers Furniture',
    position: 'Store Manager',
    status: 'active',
    tags: ['furniture', 'retail'],
    createdAt: new Date('2024-04-18'),
    updatedAt: new Date('2024-07-16'),
    assignedTo: '2',
  },
  {
    id: '34',
    name: 'Barbara Reed',
    email: 'barbara.reed@cleaning.com',
    phone: '+1 (555) 234-5678',
    company: 'Reed Cleaning Services',
    position: 'Operations Manager',
    status: 'prospect',
    tags: ['cleaning', 'services'],
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-07-17'),
    assignedTo: '1',
  },
  {
    id: '35',
    name: 'Richard Cook',
    email: 'richard.cook@plumbing.com',
    phone: '+1 (555) 345-6789',
    company: 'Cook Plumbing',
    position: 'Master Plumber',
    status: 'active',
    tags: ['plumbing', 'services'],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-07-18'),
    assignedTo: '2',
  },
  {
    id: '36',
    name: 'Susan Bailey',
    email: 'susan.bailey@photography.com',
    phone: '+1 (555) 456-7890',
    company: 'Bailey Photography',
    position: 'Lead Photographer',
    status: 'prospect',
    tags: ['photography', 'creative'],
    createdAt: new Date('2024-02-18'),
    updatedAt: new Date('2024-07-19'),
    assignedTo: '1',
  },
  {
    id: '37',
    name: 'Kenneth Rivera',
    email: 'kenneth.rivera@landscaping.com',
    phone: '+1 (555) 567-8901',
    company: 'Rivera Landscaping',
    position: 'Landscape Designer',
    status: 'active',
    tags: ['landscaping', 'design'],
    createdAt: new Date('2024-03-28'),
    updatedAt: new Date('2024-07-20'),
    assignedTo: '2',
  },
  {
    id: '38',
    name: 'Dorothy Cooper',
    email: 'dorothy.cooper@veterinary.com',
    phone: '+1 (555) 678-9012',
    company: 'Cooper Veterinary Clinic',
    position: 'Veterinarian',
    status: 'prospect',
    tags: ['veterinary', 'healthcare'],
    createdAt: new Date('2024-04-12'),
    updatedAt: new Date('2024-07-21'),
    assignedTo: '1',
  },
  {
    id: '39',
    name: 'Paul Richardson',
    email: 'paul.richardson@bakery.com',
    phone: '+1 (555) 789-0123',
    company: 'Richardson Bakery',
    position: 'Head Baker',
    status: 'active',
    tags: ['bakery', 'food'],
    createdAt: new Date('2024-05-22'),
    updatedAt: new Date('2024-07-22'),
    assignedTo: '2',
  },
  {
    id: '40',
    name: 'Nancy Cox',
    email: 'nancy.cox@fitness.com',
    phone: '+1 (555) 890-1234',
    company: 'Cox Fitness Center',
    position: 'Fitness Director',
    status: 'prospect',
    tags: ['fitness', 'wellness'],
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-07-23'),
    assignedTo: '1',
  },
  {
    id: '41',
    name: 'Frank Ward',
    email: 'frank.ward@pharmacy.com',
    phone: '+1 (555) 901-2345',
    company: 'Ward Pharmacy',
    position: 'Pharmacist',
    status: 'active',
    tags: ['pharmacy', 'healthcare'],
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-07-24'),
    assignedTo: '2',
  },
  {
    id: '42',
    name: 'Margaret Torres',
    email: 'margaret.torres@accounting.com',
    phone: '+1 (555) 012-3456',
    company: 'Torres Accounting',
    position: 'CPA',
    status: 'prospect',
    tags: ['accounting', 'finance'],
    createdAt: new Date('2024-03-12'),
    updatedAt: new Date('2024-07-25'),
    assignedTo: '1',
  },
  {
    id: '43',
    name: 'George Peterson',
    email: 'george.peterson@hardware.com',
    phone: '+1 (555) 123-4567',
    company: 'Peterson Hardware',
    position: 'Store Owner',
    status: 'active',
    tags: ['hardware', 'retail'],
    createdAt: new Date('2024-04-28'),
    updatedAt: new Date('2024-07-26'),
    assignedTo: '2',
  },
  {
    id: '44',
    name: 'Ruth Gray',
    email: 'ruth.gray@childcare.com',
    phone: '+1 (555) 234-5678',
    company: 'Gray Childcare Center',
    position: 'Director',
    status: 'prospect',
    tags: ['childcare', 'education'],
    createdAt: new Date('2024-05-08'),
    updatedAt: new Date('2024-07-27'),
    assignedTo: '1',
  },
  {
    id: '45',
    name: 'Raymond James',
    email: 'raymond.james@electrical.com',
    phone: '+1 (555) 345-6789',
    company: 'James Electrical',
    position: 'Electrician',
    status: 'active',
    tags: ['electrical', 'services'],
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-07-28'),
    assignedTo: '2',
  },
  {
    id: '46',
    name: 'Marie Watson',
    email: 'marie.watson@catering.com',
    phone: '+1 (555) 456-7890',
    company: 'Watson Catering',
    position: 'Executive Chef',
    status: 'prospect',
    tags: ['catering', 'food'],
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-07-29'),
    assignedTo: '1',
  },
  {
    id: '47',
    name: 'Larry Brooks',
    email: 'larry.brooks@printing.com',
    phone: '+1 (555) 567-8901',
    company: 'Brooks Printing',
    position: 'Print Manager',
    status: 'active',
    tags: ['printing', 'services'],
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-07-30'),
    assignedTo: '2',
  },
  {
    id: '48',
    name: 'Alice Kelly',
    email: 'alice.kelly@jewelry.com',
    phone: '+1 (555) 678-9012',
    company: 'Kelly Jewelry',
    position: 'Jewelry Designer',
    status: 'prospect',
    tags: ['jewelry', 'luxury'],
    createdAt: new Date('2024-04-08'),
    updatedAt: new Date('2024-07-31'),
    assignedTo: '1',
  },
  {
    id: '49',
    name: 'Jerry Howard',
    email: 'jerry.howard@roofing.com',
    phone: '+1 (555) 789-0123',
    company: 'Howard Roofing',
    position: 'Roofing Contractor',
    status: 'active',
    tags: ['roofing', 'construction'],
    createdAt: new Date('2024-05-18'),
    updatedAt: new Date('2024-08-01'),
    assignedTo: '2',
  },
  {
    id: '50',
    name: 'Janice Ward',
    email: 'janice.ward@salon.com',
    phone: '+1 (555) 890-1234',
    company: 'Ward Hair Salon',
    position: 'Salon Owner',
    status: 'prospect',
    tags: ['salon', 'beauty'],
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-08-02'),
    assignedTo: '1',
  },
];

// Mock Deals
export const mockDeals: Deal[] = [
  {
    id: '1',
    title: 'TechCorp Enterprise License',
    value: 50000,
    stage: 'negotiation',
    contactId: '1',
    probability: 75,
    expectedCloseDate: new Date('2024-07-31'),
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-15'),
    assignedTo: '2',
    notes: 'Large enterprise deal, needs approval from board',
  },
  {
    id: '2',
    title: 'Startup.io Growth Plan',
    value: 12000,
    stage: 'proposal',
    contactId: '2',
    probability: 60,
    expectedCloseDate: new Date('2024-07-15'),
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-16'),
    assignedTo: '2',
  },
  {
    id: '3',
    title: 'BigCorp Integration',
    value: 75000,
    stage: 'qualified',
    contactId: '3',
    probability: 40,
    expectedCloseDate: new Date('2024-08-30'),
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-17'),
    assignedTo: '1',
  },
];

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: '1',
    type: 'call',
    title: 'Follow-up call with John Smith',
    description: 'Discussed implementation timeline',
    contactId: '1',
    dealId: '1',
    dueDate: new Date('2024-06-20'),
    createdAt: new Date('2024-06-18'),
    assignedTo: '2',
    priority: 'high',
  },
  {
    id: '2',
    type: 'email',
    title: 'Send proposal to Emily',
    description: 'Growth plan proposal with pricing',
    contactId: '2',
    dealId: '2',
    dueDate: new Date('2024-06-19'),
    createdAt: new Date('2024-06-18'),
    assignedTo: '2',
    priority: 'medium',
  },
  {
    id: '3',
    type: 'meeting',
    title: 'Demo meeting with BigCorp',
    description: 'Product demonstration and Q&A',
    contactId: '3',
    dealId: '3',
    dueDate: new Date('2024-06-25'),
    createdAt: new Date('2024-06-18'),
    assignedTo: '1',
    priority: 'high',
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalContacts: 50,
  activeDeals: 23,
  totalRevenue: 1250000,
  monthlyGrowth: 12.5,
  conversionRate: 23.4,
  avgDealSize: 45000,
};
