import { ReportTemplate, Report, ReportData } from './types';

export const mockReportTemplates: ReportTemplate[] = [
  {
    id: 'sales-performance',
    name: 'Sales Performance Report',
    description: 'Track sales metrics and performance over time',
    category: 'sales',
    chartType: 'bar',
    fields: [
      { id: 'agent', name: 'agent', label: 'Agent Name', type: 'string', required: true },
      { id: 'sales', name: 'sales', label: 'Total Sales', type: 'currency', required: true },
      { id: 'units', name: 'units', label: 'Units Sold', type: 'number', required: true },
      { id: 'commission', name: 'commission', label: 'Commission Earned', type: 'currency', required: true },
      { id: 'avgPrice', name: 'avgPrice', label: 'Average Sale Price', type: 'currency', required: false },
    ],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'property-inventory',
    name: 'Property Inventory Report',
    description: 'Overview of property listings and status',
    category: 'properties',
    chartType: 'pie',
    fields: [
      { id: 'status', name: 'status', label: 'Status', type: 'string', required: true, options: ['Active', 'Pending', 'Sold', 'Off Market'] },
      { id: 'count', name: 'count', label: 'Count', type: 'number', required: true },
      { id: 'avgPrice', name: 'avgPrice', label: 'Average Price', type: 'currency', required: true },
      { id: 'totalValue', name: 'totalValue', label: 'Total Value', type: 'currency', required: true },
    ],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'market-trends',
    name: 'Market Trends Report',
    description: 'Analyze market trends and pricing patterns',
    category: 'market',
    chartType: 'line',
    fields: [
      { id: 'month', name: 'month', label: 'Month', type: 'date', required: true },
      { id: 'avgPrice', name: 'avgPrice', label: 'Average Price', type: 'currency', required: true },
      { id: 'volume', name: 'volume', label: 'Sales Volume', type: 'number', required: true },
      { id: 'daysOnMarket', name: 'daysOnMarket', label: 'Avg Days on Market', type: 'number', required: true },
    ],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'agent-productivity',
    name: 'Agent Productivity Report',
    description: 'Track individual agent performance and productivity',
    category: 'agents',
    chartType: 'table',
    fields: [
      { id: 'agent', name: 'agent', label: 'Agent Name', type: 'string', required: true },
      { id: 'listings', name: 'listings', label: 'Active Listings', type: 'number', required: true },
      { id: 'closings', name: 'closings', label: 'Monthly Closings', type: 'number', required: true },
      { id: 'revenue', name: 'revenue', label: 'Revenue Generated', type: 'currency', required: true },
      { id: 'clientMeetings', name: 'clientMeetings', label: 'Client Meetings', type: 'number', required: true },
    ],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'financial-summary',
    name: 'Financial Summary Report',
    description: 'Comprehensive financial overview and analytics',
    category: 'financial',
    chartType: 'area',
    fields: [
      { id: 'category', name: 'category', label: 'Category', type: 'string', required: true },
      { id: 'revenue', name: 'revenue', label: 'Revenue', type: 'currency', required: true },
      { id: 'expenses', name: 'expenses', label: 'Expenses', type: 'currency', required: true },
      { id: 'profit', name: 'profit', label: 'Net Profit', type: 'currency', required: true },
      { id: 'margin', name: 'margin', label: 'Profit Margin %', type: 'number', required: true },
    ],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-28'),
  },
];

export const mockReportData: Record<string, ReportData[]> = {
  'sales-performance': [
    { agent: 'Sarah Johnson', sales: 2850000, units: 8, commission: 85500, avgPrice: 356250 },
    { agent: 'Mike Chen', sales: 3200000, units: 10, commission: 96000, avgPrice: 320000 },
    { agent: 'Emily Rodriguez', sales: 1950000, units: 6, commission: 58500, avgPrice: 325000 },
    { agent: 'David Kim', sales: 2650000, units: 7, commission: 79500, avgPrice: 378571 },
    { agent: 'Lisa Thompson', sales: 4100000, units: 12, commission: 123000, avgPrice: 341667 },
  ],
  'property-inventory': [
    { status: 'Active', count: 45, avgPrice: 425000, totalValue: 19125000 },
    { status: 'Pending', count: 12, avgPrice: 380000, totalValue: 4560000 },
    { status: 'Sold', count: 38, avgPrice: 395000, totalValue: 15010000 },
    { status: 'Off Market', count: 8, avgPrice: 350000, totalValue: 2800000 },
  ],
  'market-trends': [
    { month: new Date('2024-01-01'), avgPrice: 385000, volume: 42, daysOnMarket: 28 },
    { month: new Date('2024-02-01'), avgPrice: 392000, volume: 38, daysOnMarket: 25 },
    { month: new Date('2024-03-01'), avgPrice: 405000, volume: 45, daysOnMarket: 22 },
    { month: new Date('2024-04-01'), avgPrice: 415000, volume: 52, daysOnMarket: 20 },
    { month: new Date('2024-05-01'), avgPrice: 425000, volume: 48, daysOnMarket: 18 },
    { month: new Date('2024-06-01'), avgPrice: 435000, volume: 55, daysOnMarket: 16 },
  ],
  'agent-productivity': [
    { agent: 'Sarah Johnson', listings: 12, closings: 3, revenue: 95000, clientMeetings: 28 },
    { agent: 'Mike Chen', listings: 15, closings: 4, revenue: 125000, clientMeetings: 35 },
    { agent: 'Emily Rodriguez', listings: 8, closings: 2, revenue: 65000, clientMeetings: 22 },
    { agent: 'David Kim', listings: 10, closings: 3, revenue: 85000, clientMeetings: 25 },
    { agent: 'Lisa Thompson', listings: 18, closings: 5, revenue: 155000, clientMeetings: 42 },
  ],
  'financial-summary': [
    { category: 'Property Sales', revenue: 15750000, expenses: 1260000, profit: 14490000, margin: 92.0 },
    { category: 'Rentals', revenue: 2850000, expenses: 1140000, profit: 1710000, margin: 60.0 },
    { category: 'Property Management', revenue: 650000, expenses: 325000, profit: 325000, margin: 50.0 },
    { category: 'Consulting', revenue: 450000, expenses: 180000, profit: 270000, margin: 60.0 },
  ],
};

export const mockReports: Report[] = [
  {
    id: 'report-1',
    templateId: 'sales-performance',
    name: 'Q1 Sales Performance',
    description: 'Sales performance analysis for Q1 2024',
    data: mockReportData['sales-performance'],
    config: {
      dateRange: {
        start: new Date('2024-01-01'),
        end: new Date('2024-03-31'),
      },
      filters: [],
      chartType: 'bar',
      showTotals: true,
    },
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
    generatedBy: 'Dawn Rodriguez',
  },
  {
    id: 'report-2',
    templateId: 'property-inventory',
    name: 'Current Property Status',
    description: 'Current inventory breakdown by status',
    data: mockReportData['property-inventory'],
    config: {
      dateRange: {
        start: new Date('2024-06-01'),
        end: new Date('2024-06-30'),
      },
      filters: [],
      chartType: 'pie',
      showTotals: false,
    },
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-15'),
    generatedBy: 'Dawn Rodriguez',
  },
  {
    id: 'report-3',
    templateId: 'market-trends',
    name: 'Market Trends Analysis',
    description: '6-month market trend analysis',
    data: mockReportData['market-trends'],
    config: {
      dateRange: {
        start: new Date('2024-01-01'),
        end: new Date('2024-06-30'),
      },
      filters: [],
      chartType: 'line',
      showTotals: false,
    },
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-20'),
    generatedBy: 'Dawn Rodriguez',
  },
];