
import { Contact } from '@/types/crm';

export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@techcorp.com',
    phone: '+1 (555) 123-4567',
    company: 'TechCorp Inc.',
    position: 'CTO',
    status: 'active',
    tags: ['enterprise', 'tech'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-15'),
    assignedTo: '2',
    notes: 'Interested in enterprise solution',
  },
  {
    id: '2',
    name: 'Emily Davis',
    email: 'emily@startup.io',
    phone: '+1 (555) 987-6543',
    company: 'Startup.io',
    position: 'Founder',
    status: 'prospect',
    tags: ['startup', 'saas'],
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-06-16'),
    assignedTo: '2',
  },
  {
    id: '3',
    name: 'Robert Wilson',
    email: 'robert@bigcorp.com',
    phone: '+1 (555) 456-7890',
    company: 'BigCorp',
    position: 'VP Sales',
    status: 'active',
    tags: ['enterprise', 'established'],
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-06-17'),
    assignedTo: '1',
  },
  {
    id: '4',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@healthplus.com',
    phone: '+1 (555) 234-5678',
    company: 'HealthPlus Solutions',
    position: 'Director of Operations',
    status: 'active',
    tags: ['healthcare', 'mid-market'],
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-06-18'),
    assignedTo: '1',
  },
  {
    id: '5',
    name: 'David Martinez',
    email: 'david.martinez@fintech.com',
    phone: '+1 (555) 345-6789',
    company: 'FinTech Innovations',
    position: 'Product Manager',
    status: 'prospect',
    tags: ['fintech', 'innovation'],
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-06-19'),
    assignedTo: '2',
  },
  {
    id: '6',
    name: 'Jennifer Brown',
    email: 'jennifer.brown@retailco.com',
    phone: '+1 (555) 456-7890',
    company: 'RetailCo',
    position: 'Marketing Director',
    status: 'active',
    tags: ['retail', 'marketing'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-20'),
    assignedTo: '1',
  },
  {
    id: '7',
    name: 'Michael Johnson',
    email: 'michael.johnson@educorp.com',
    phone: '+1 (555) 567-8901',
    company: 'EduCorp',
    position: 'VP Technology',
    status: 'prospect',
    tags: ['education', 'technology'],
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-06-21'),
    assignedTo: '2',
  },
  {
    id: '8',
    name: 'Sarah Thompson',
    email: 'sarah.thompson@consulting.com',
    phone: '+1 (555) 678-9012',
    company: 'Thompson Consulting',
    position: 'Senior Partner',
    status: 'active',
    tags: ['consulting', 'enterprise'],
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-22'),
    assignedTo: '1',
  },
  {
    id: '9',
    name: 'Kevin Lee',
    email: 'kevin.lee@logistics.com',
    phone: '+1 (555) 789-0123',
    company: 'Global Logistics',
    position: 'Operations Manager',
    status: 'inactive',
    tags: ['logistics', 'operations'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-05-15'),
    assignedTo: '2',
  },
  {
    id: '10',
    name: 'Amanda Clark',
    email: 'amanda.clark@mediagroup.com',
    phone: '+1 (555) 890-1234',
    company: 'Media Group Inc',
    position: 'Creative Director',
    status: 'prospect',
    tags: ['media', 'creative'],
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-06-23'),
    assignedTo: '1',
  },
  {
    id: '11',
    name: 'Christopher White',
    email: 'chris.white@manufacturing.com',
    phone: '+1 (555) 901-2345',
    company: 'White Manufacturing',
    position: 'Plant Manager',
    status: 'active',
    tags: ['manufacturing', 'industrial'],
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-06-24'),
    assignedTo: '2',
  },
  {
    id: '12',
    name: 'Nicole Garcia',
    email: 'nicole.garcia@pharma.com',
    phone: '+1 (555) 012-3456',
    company: 'PharmaCorp',
    position: 'Research Director',
    status: 'prospect',
    tags: ['pharmaceutical', 'research'],
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-06-25'),
    assignedTo: '1',
  },
  {
    id: '13',
    name: 'Ryan Miller',
    email: 'ryan.miller@energy.com',
    phone: '+1 (555) 123-4567',
    company: 'Green Energy Solutions',
    position: 'Project Manager',
    status: 'active',
    tags: ['energy', 'green-tech'],
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-06-26'),
    assignedTo: '2',
  },
  {
    id: '14',
    name: 'Jessica Taylor',
    email: 'jessica.taylor@insurance.com',
    phone: '+1 (555) 234-5678',
    company: 'Taylor Insurance',
    position: 'Account Executive',
    status: 'prospect',
    tags: ['insurance', 'finance'],
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-27'),
    assignedTo: '1',
  },
  {
    id: '15',
    name: 'Daniel Rodriguez',
    email: 'daniel.rodriguez@construction.com',
    phone: '+1 (555) 345-6789',
    company: 'Rodriguez Construction',
    position: 'Site Supervisor',
    status: 'active',
    tags: ['construction', 'real-estate'],
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-06-28'),
    assignedTo: '2',
  },
  {
    id: '16',
    name: 'Lauren Wilson',
    email: 'lauren.wilson@hospitality.com',
    phone: '+1 (555) 456-7890',
    company: 'Luxury Hospitality Group',
    position: 'General Manager',
    status: 'prospect',
    tags: ['hospitality', 'luxury'],
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-06-29'),
    assignedTo: '1',
  },
  {
    id: '17',
    name: 'Brian Moore',
    email: 'brian.moore@automotive.com',
    phone: '+1 (555) 567-8901',
    company: 'Moore Automotive',
    position: 'Service Manager',
    status: 'active',
    tags: ['automotive', 'service'],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-06-30'),
    assignedTo: '2',
  },
  {
    id: '18',
    name: 'Stephanie Hall',
    email: 'stephanie.hall@legal.com',
    phone: '+1 (555) 678-9012',
    company: 'Hall Legal Services',
    position: 'Managing Partner',
    status: 'prospect',
    tags: ['legal', 'professional-services'],
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-07-01'),
    assignedTo: '1',
  },
  {
    id: '19',
    name: 'Andrew Young',
    email: 'andrew.young@nonprofit.org',
    phone: '+1 (555) 789-0123',
    company: 'Community Foundation',
    position: 'Executive Director',
    status: 'active',
    tags: ['nonprofit', 'community'],
    createdAt: new Date('2024-05-05'),
    updatedAt: new Date('2024-07-02'),
    assignedTo: '2',
  },
  {
    id: '20',
    name: 'Michelle King',
    email: 'michelle.king@fashion.com',
    phone: '+1 (555) 890-1234',
    company: 'King Fashion House',
    position: 'Design Director',
    status: 'prospect',
    tags: ['fashion', 'design'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-07-03'),
    assignedTo: '1',
  },
  {
    id: '21',
    name: 'Thomas Scott',
    email: 'thomas.scott@agriculture.com',
    phone: '+1 (555) 901-2345',
    company: 'Scott Farms',
    position: 'Farm Manager',
    status: 'active',
    tags: ['agriculture', 'farming'],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-07-04'),
    assignedTo: '2',
  },
  {
    id: '22',
    name: 'Rachel Green',
    email: 'rachel.green@publishing.com',
    phone: '+1 (555) 012-3456',
    company: 'Green Publishing',
    position: 'Editor-in-Chief',
    status: 'prospect',
    tags: ['publishing', 'media'],
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-07-05'),
    assignedTo: '1',
  },
  {
    id: '23',
    name: 'Steven Adams',
    email: 'steven.adams@sports.com',
    phone: '+1 (555) 123-4567',
    company: 'Adams Sports Management',
    position: 'Sports Agent',
    status: 'active',
    tags: ['sports', 'entertainment'],
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-07-06'),
    assignedTo: '2',
  },
  {
    id: '24',
    name: 'Kimberly Baker',
    email: 'kimberly.baker@food.com',
    phone: '+1 (555) 234-5678',
    company: 'Baker Foods Inc',
    position: 'Quality Manager',
    status: 'prospect',
    tags: ['food', 'manufacturing'],
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-07-07'),
    assignedTo: '1',
  },
  {
    id: '25',
    name: 'Mark Turner',
    email: 'mark.turner@transport.com',
    phone: '+1 (555) 345-6789',
    company: 'Turner Transport',
    position: 'Fleet Manager',
    status: 'active',
    tags: ['transportation', 'logistics'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-07-08'),
    assignedTo: '2',
  },
];
