name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://lovable.dev/projects/ee44240e-cd82-43c4-8e94-050e970f07c8
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build production bundle
        run: npm run build
        env:
          NODE_ENV: production
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}
          VITE_SUPABASE_PROJECT_ID: ${{ secrets.VITE_SUPABASE_PROJECT_ID }}
      
      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
          retention-days: 30
      
      - name: Deployment notification
        if: success()
        run: |
          echo "✅ Deployment successful to production"
          echo "🚀 Build size: $(du -sh dist/ | cut -f1)"
          echo "📦 Files: $(find dist/ -type f | wc -l)"
      
      - name: Deployment failed notification
        if: failure()
        run: |
          echo "❌ Deployment failed"
          echo "Please check the logs above for errors"
